name: FMC-Plugin
version: 0.0.1
main: net.ttk2.Main
author: Bella
website: keypforev.ddns.net
api-version: '1.21'
description: "§6§lThis plugin is provided by FMC Server!!"
commands:
  fmc:
    usage: /<command> [potion|fly|reload]
    description: can fly in survival